create table REVIEWS
(
    ID        SERIAL PRIMARY KEY,
    USER_NAME VARCHAR(255) NOT NULL,
    MOVIE_ID  INT          NOT NULL,
    COMMENT   VARCHAR      NOT NULL,

    CONSTRAINT FK_USER_NAME
        FOREIGN KEY (USER_NAME)
            REFERENCES USERS (USER_NAME) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_MOVIE
        FOREIGN KEY (MOVIE_ID)
            REFERENCES MOVIES (ID) ON DELETE CASCADE
);