CREATE TABLE COUNTRY_TO_MOVIE
(
    COUNTRY_ID INT NOT NULL,
    MOVIE_ID   INT NOT NULL,
    CONSTRAINT COUNTRY_TO_MOVIE_PKEY PRIMARY KEY (COUNTRY_ID, MOVIE_ID),
    CONSTRAINT FK_COUNTRY
        FOREIGN KEY (COUNTRY_ID)
            REFERENCES COUNTRIES (ID) ON DELETE RESTRICT,
    CONSTRAINT FK_MOVIE
        FOREIGN KEY (MOVIE_ID)
            REFERENCES MOVIES (ID) ON DELETE CASCADE
);