CREATE TABLE GENRE_TO_MOVIE
(
    GENRE_ID INT NOT NULL,
    MOVIE_ID INT NOT NULL,
    CONSTRAINT GENRE_TO_MOVIE_PKEY PRIMARY KEY (GENRE_ID, MOVIE_ID),
    CONSTRAINT FK_GENRE
        FOREIGN KEY (GENRE_ID)
            REFERENCES GENRES (ID) ON DELETE RESTRICT,
    CONSTRAINT FK_MOVIE
        FOREIGN KEY (MOVIE_ID)
            REFERENCES MOVIES (ID) ON DELETE CASCADE
);